### ISSUE TITLE
TypeError 'map' of null

### ISSUE THREAD

**Issue by markgoho** [MurhafSousli/ng2-wp-api#27]
Getting this in the console on first page load:

`Error: Uncaught (in promise): TypeError: Cannot read property 'map' of null`
`TypeError: Cannot read property 'map' of null`
`    at new ConfigService (http://localhost:4200/vendor.bundle.js:26138:30)`
`    at wpConfigFactory (http://localhost:4200/vendor.bundle.js:96289:12)`

I'm initializing the module exactly how the docs state:
`WordPressModule.forRoot('https://www.gideonlabs.com/', null, true),`

**Comment by markgoho** [comment]
`WordPressModule.forRoot('https://www.gideonlabs.com/'),`

This gives the same TypeError message, so it must not be due to how I'm initializing the Module.

**Comment by markgoho** [comment]
Using photonOptions() as instructed in the docs removes the error:

```
export function photonOptions() {
  return [
    { 'key': 'large', 'value': { w: 800, h: 360 } },
    { 'key': 'cropped', 'value': { crop: "160px,25,1400px,60" } },
    { 'key': 'resized', 'value': { resize: "400,220" } }
  ]
}

WordPressModule.forRoot('https://www.gideonlabs.com/', photonOptions(), true),
```
No error when doing it this way.
